clear all 
close all 
clc

%% Create GUI structure
scrn_size = get(0, 'ScreenSize');
xmiddle = scrn_size(3) / 2;
ymiddle = scrn_size(4) / 2;
sizex = 1250;
sizey = 850;

 f = figure( ...
        'Name', 'Fenetrage des signaux VisuResp et Biopac', ...
        'Visible', 'on', ...
        'Position', [xmiddle - (sizex / 2), ymiddle - (sizey / 2), sizex, sizey], ...
        'NumberTitle', 'Off' ...
        );
    
    %%%%%%%%%%%%%%%%%
%               %
%   Panel for   %
%    signals    %
%               %
%%%%%%%%%%%%%%%%%

% variabe used to place the panel that will display the 4 waves
widthsignal = 825;
heightsignal = 325;

% creation of the panel that display the 4 waves and the information
% relative to the signal such as the starting time, ending time and he
% exportation
psignalB = uipanel( ...
    'Parent', f, ...
    'Title', 'Signal Biopac (signal B)', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 500, widthsignal, heightsignal] ...
    );
psignalBthorax = uipanel( ...
    'Parent', psignalB, ...
    'Title', 'Signal Biopac Thorax', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 170, 800, 140] ...
    );
psignalBabdo = uipanel( ...
    'Parent', psignalB, ...
    'Title', 'Signal Biopac Abdo', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 5, 800, 140] ...
    );

psignalA = uipanel( ...
    'Parent', f, ...
    'Title', 'Signal VisuResp (signal A)', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 150, widthsignal, heightsignal] ...
    );

psignalAthorax = uipanel( ...
    'Parent', psignalA, ...
    'Title', 'Signal VisuResp Thorax', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 170, 800, 140] ...
    );
psignalAabdo = uipanel( ...
    'Parent', psignalA, ...
    'Title', 'Signal VisuResp Abdo', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [5, 5, 800, 140] ...
    );


% signal screen
%Graph signal B thorax
axe_signal_B_Thorax = axes( ...
    'Parent', psignalBthorax, ...
    'Units', 'Pixels', ...
    'FontSize', 8, ...
    'Color', 'w', ...
    'XTick', [], ...
    'Position', [30, 25, 700, 80] ...
    );

%Graph signal B abdo
axe_signal_B_Abdo = axes( ...
    'Parent', psignalBabdo, ...
    'Units', 'Pixels', ...
    'FontSize', 8, ...
    'Color', 'w', ...
    'XTick', [], ...
    'Position', [30, 25, 700, 80] ...
    );

%Graph signal A thorax
axe_signal_A_Thorax = axes( ...
    'Parent', psignalAthorax, ...
    'Units', 'Pixels', ...
    'FontSize', 8, ...
    'Color', 'w', ...
    'XTick', [], ...
    'Position', [30, 25, 700, 80] ...
    );

%Graph signal A
axe_signal_A_Abdo = axes( ...
    'Parent', psignalAabdo, ...
    'Units', 'Pixels', ...
    'FontSize', 8, ...
    'Color', 'w', ...
    'XTick', [], ...
    'Position', [30, 25, 700, 80] ...
    );

%Panel Repertoire des fichiers 
prepertoire = uipanel( ...
    'Parent', f, ...
    'Title', 'Repertoire', ...
    'Units', 'Pixels', ...
    'Fontsize', 9, ...
    'Position', [850, 10, 350, 800] ...
    );

%affiche les fichiers présents dans le dossier selectionné
listedossier = uicontrol('Parent',prepertoire,'Style','listbox','String','fichier','Position',[10 380 175 400],'Callback',{@filelist_callback});
selectdossier = uicontrol('Parent',prepertoire,'Style','pushbutton','FontSize',12,'String','Selectionner un dossier','Position',[10 320 200 40],'Callback',{@selectdir_callback});
%chargerfichier = uicontrol('Parent',repertoire,'Style','pushbutton','FontSize',12,'String','Chargement','Position',[10 295 150 30],'Callback',{@loadfile_callback});
%rafraichirdossier = uicontrol('Parent',repertoire,'Style','pushbutton','FontSize',12,'String','Changer de dossier','Position',[10 265 150 30],'Callback',{@refreshdir_callback});


% Boutton ouverture de fichier Biopac
% uicontrol( ...
%     'Parent', repertoire, ...
%     'Style', 'pushbutton', ...
%     'Fontsize', 9, ...
%     'String', 'Export Signals', ...
%     'Position', [170, 410, 80, 20], ...
%     'ToolTipString', 'Selectionner le dossier contenant les enregistrements Biopac', ...
%     'Callback', {@timebar_button_callback} ...
%     );

